import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";

import { Box, Flex, Heading } from "@chakra-ui/react";
import NewMeeting from "@/components/NewMeeting";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Aghota</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex align={"center"} as="main" h={"var(--chakra-vh)"}>
        <Flex flexDir={"column"} p={8}>
          <Heading maxW={500}>Video Calls and meetings for everyone</Heading>
          <NewMeeting router={router} />
        </Flex>
      </Flex>
    </>
  );
}
